#!/bin/bash

error=`$PWD/cs183/passcheck.rb $PWD/cs183/tests/passwd 2>&1`

if [ $? -eq 1 ]
then
	echo "Error: expected return value of 0, got 1"
	echo "Error: expected no standard error, got"	
	echo "$error" >&2
	exit 1
fi
